### ISSUE TITLE
[Bug?] Black Tentacles

### ISSUE THREAD

**Issue by MasterCroissant** [gambit07/gambits-premades#2]
I don't think this spell triggers correctly.

When a PC cast the spell on a group of creature, those creature won't roll their Dex Save until the start of their turn. However, the spell stipulates: "When a creature enters the affected area for the first time on a turn...". As such, they should be rolling a successful Dex Save on the caster's turn or take 3d6 bludgeoning damage and be restrained and take another 3d6 on their own turn. 

This work correctly when a creature enters the area of effect even when their turn haven't started yet, so it is only when the spell is cast that this issue happens. 

Finally, the DAE half movement speed is not quite correct, since a creature exiting the area of effect will regain the other half of its movement speed upon exiting. However, there is a module called Enhanced Terrain Layer that might do exactly what your looking for: https://github.com/ironmonk88/enhanced-terrain-layer
This module might have some compatibility issues with V11, but for this particular effect it works perfectly. You can change the template movement cost in feet directly on the spell configuration sheet:
![Black Tentacles - Difficult Terrain](https://github.com/gambit07/gambits-premades/assets/124537248/24a2370f-e93d-49de-b8f6-edd24305f57d)

Hope this helps, great module so far!

**Comment by gambit07** [comment]
Hey, thanks! For your first point, I initially understood it the way you are describing as well, however, in the SA 2020 Compendium it clarifies, you can find the relevant part by searching for Black Tentacles: https://media.wizards.com/2020/dnd/downloads/SA-Compendium.pdf

For your second point, yeah I'm aware that unfortunately the DAE half movement is a bandaid solution. Right now there's nothing in core to account for this, and ETL has been abandoned for V11. Happy it works for your purposes but I'm not going to add it into the item because I'm not sure what other adverse effects it could have on a V11 world at this point and since it's not being maintained. I'm hoping the planned changes for V12 will allow for a full implementation of this item. 

I should also have an update coming for this item soon anyway, this is one of my older automations and needs a bit of love

**Comment by MasterCroissant** [comment]
Well I'll be damned, never would I have ever though that the spell was supposed to work this way. Thanks for the clarification. And for ETL I perfectly understand from where you stand about this. At least there's a way for those who might want to try it for themselves.

Have a great day!

**Comment by gambit07** [comment]
Thanks, you too!
