### ISSUE TITLE
Dfreds Convenient Effects 

### ISSUE THREAD

**Issue by CaosFR** [gambit07/gambits-premades#31]
Hi,

Thanks for your great module. Why the Foundry v12 version of your module dont work with Dfreds Convenient Effects. Sadly without DFred they are no automate condition like paralyze.

For example, “Cause Fear” features the “macro. StatusEffect” which applies ‘frightened’ (no automation) instead of macro. CE “frightened” (fully automated conditions).

Do you plan to integrate DFred ?

**Comment by gambit07** [comment]
Hi there, Bugbears Scripts or Chris Premades should be used for status effects in v12. Either module will add in the appropriate flags for system statuses

**Comment by CaosFR** [comment]
I have install Bugbears Scripts, it's amazing. 

I always thought it would be great to integrate the effects into the basic conditions!

**Comment by gambit07** [comment]
> I have install Bugbears Scripts, it's amazing. I always thought it would be great to integrate the effects into the basic conditions ! 
> 
> Does [automated-conditions-5e](https://github.com/thatlonelybugbear/automated-conditions-5e) work with your module to (same author) ? Chris Premades dont work with v12 for now.
> 
> I think you shoud add this two modules to the dependencies V12

Dfreds was sort of the default option pre v12 which is why it was used as a dependency, since it took a while to get to v12 there are now multiple alternatives so I don't want to lock anyone into a specific module for those core effects. Automated Conditions should work fine, but that module isn't really necessary when using midi qol. Chris Premades is in beta and is pretty far along, you can grab the beta link to install their module on their discord here: https://discord.gg/KtyknfFH
